services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    devices:
      - "/dev/kmsg"

  prometheus_a:
    container_name: prometheus_a
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - cadvisor

  prometheus_b:
    container_name: prometheus_b
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - cadvisor
